// Root file for execution-specs tests
// This imports all generated test files
// Auto-generated by scripts/update_spec_root.py

const std = @import("std");
const testing = std.testing;

// Re-export runner for generated tests
pub const runner = @import("runner.zig");

// Infrastructure test
test "spec runner infrastructure" {
    try testing.expect(true);
}

// Import generated tests
test { _ = @import("generated/blockchain_tests/eest/berlin/eip2929_gas_cost_increases/precompile_warming/precompile_warming.zig"); }
test { _ = @import("generated/blockchain_tests/eest/berlin/eip2930_access_list/acl/account_storage_warm_cold_state.zig"); }
test { _ = @import("generated/blockchain_tests/eest/berlin/eip2930_access_list/acl/transaction_intrinsic_gas_cost.zig"); }
test { _ = @import("generated/blockchain_tests/eest/berlin/eip2930_access_list/tx_intrinsic_gas/tx_intrinsic_gas.zig"); }
test { _ = @import("generated/blockchain_tests/eest/byzantium/eip198_modexp_precompile/modexp/modexp.zig"); }
test { _ = @import("generated/blockchain_tests/eest/cancun/eip1153_tstore/basic_tload/basic_tload_after_store.zig"); }
test { _ = @import("generated/blockchain_tests/eest/cancun/eip1153_tstore/basic_tload/basic_tload_gasprice.zig"); }
test { _ = @import("generated/blockchain_tests/eest/cancun/eip1153_tstore/basic_tload/basic_tload_other_after_tstore.zig"); }
test { _ = @import("generated/blockchain_tests/eest/cancun/eip1153_tstore/basic_tload/basic_tload_transaction_begin.zig"); }
test { _ = @import("generated/blockchain_tests/eest/cancun/eip1153_tstore/basic_tload/basic_tload_works.zig"); }
test { _ = @import("generated/blockchain_tests/eest/cancun/eip1153_tstore/tload_calls/tload_calls.zig"); }
test { _ = @import("generated/blockchain_tests/eest/cancun/eip1153_tstore/tload_reentrancy/tload_reentrancy.zig"); }
test { _ = @import("generated/blockchain_tests_engine/eest/berlin/eip2929_gas_cost_increases/precompile_warming/precompile_warming.zig"); }
test { _ = @import("generated/blockchain_tests_engine/eest/berlin/eip2930_access_list/acl/account_storage_warm_cold_state.zig"); }
test { _ = @import("generated/blockchain_tests_engine/eest/berlin/eip2930_access_list/acl/transaction_intrinsic_gas_cost.zig"); }
test { _ = @import("generated/blockchain_tests_engine/eest/berlin/eip2930_access_list/tx_intrinsic_gas/tx_intrinsic_gas.zig"); }
test { _ = @import("generated/blockchain_tests_engine/eest/byzantium/eip198_modexp_precompile/modexp/modexp.zig"); }
test { _ = @import("generated/blockchain_tests_engine/eest/cancun/eip1153_tstore/basic_tload/basic_tload_after_store.zig"); }
test { _ = @import("generated/blockchain_tests_engine/eest/cancun/eip1153_tstore/basic_tload/basic_tload_gasprice.zig"); }
test { _ = @import("generated/blockchain_tests_engine/eest/cancun/eip1153_tstore/basic_tload/basic_tload_other_after_tstore.zig"); }
test { _ = @import("generated/blockchain_tests_engine/eest/cancun/eip1153_tstore/basic_tload/basic_tload_transaction_begin.zig"); }
test { _ = @import("generated/blockchain_tests_engine/eest/cancun/eip1153_tstore/basic_tload/basic_tload_works.zig"); }
test { _ = @import("generated/blockchain_tests_engine/eest/cancun/eip1153_tstore/tload_calls/tload_calls.zig"); }
test { _ = @import("generated/blockchain_tests_engine/eest/cancun/eip1153_tstore/tload_reentrancy/tload_reentrancy.zig"); }
test { _ = @import("generated/state_tests/eest/berlin/eip2930_access_list/acl/account_storage_warm_cold_state.zig"); }
test { _ = @import("generated/state_tests/eest/berlin/eip2930_access_list/acl/transaction_intrinsic_gas_cost.zig"); }
test { _ = @import("generated/state_tests/eest/berlin/eip2930_access_list/tx_intrinsic_gas/tx_intrinsic_gas.zig"); }
test { _ = @import("generated/state_tests/eest/byzantium/eip198_modexp_precompile/modexp/modexp.zig"); }
test { _ = @import("generated/state_tests/eest/cancun/eip1153_tstore/basic_tload/basic_tload_after_store.zig"); }
test { _ = @import("generated/state_tests/eest/cancun/eip1153_tstore/basic_tload/basic_tload_gasprice.zig"); }
test { _ = @import("generated/state_tests/eest/cancun/eip1153_tstore/basic_tload/basic_tload_other_after_tstore.zig"); }
test { _ = @import("generated/state_tests/eest/cancun/eip1153_tstore/basic_tload/basic_tload_transaction_begin.zig"); }
test { _ = @import("generated/state_tests/eest/cancun/eip1153_tstore/basic_tload/basic_tload_works.zig"); }
test { _ = @import("generated/state_tests/eest/cancun/eip1153_tstore/tload_calls/tload_calls.zig"); }
test { _ = @import("generated/state_tests/eest/cancun/eip1153_tstore/tload_reentrancy/tload_reentrancy.zig"); }
